export const config = {
    AWS_PEDIDOS_QUEUE : process.env.AWS_PEDIDOS_QUEUE,
    AWS_PEDIDOS_QUEUE_URL : process.env.AWS_PEDIDOS_QUEUE_URL,
    AWS_PEDIDOS_RESPONSE_QUEUE : process.env.AWS_PEDIDOS_RESPONSE_QUEUE,
    AWS_PEDIDOS_RESPONSE_QUEUE_URL : process.env.AWS_PEDIDOS_RESPONSE_QUEUE_URL,
    AWS_REGION: process.env.AWS_REGION,
    ACCESS_KEY_ID: process.env.ACCESS_KEY_ID,
    SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY,
};