apiVersion: v1
kind: Service
metadata:
  labels:
    app: fiap-application
  name: fiap-application
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fiap-application
  type: NodePort
