apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-cm
data:
  init.js: |
    db = db.getSiblingDB('fiap');
    db.createUser({
      user: "alyne",
      pwd: "123456",
      roles: [{ role: "readWrite", db: "fiap" }]
    });
  init-mongo.sh: |
    #!/bin/bash
    set -e

    mongo <<EOF
    var username = '$MONGO_INITDB_APP_USERNAME';
    var password = '$MONGO_INITDB_APP_PASSWORD';
    var database = '$MONGO_INITDB_APP_DATABASE';
    db = db.getSiblingDB(database);
    db.createUser({
      user: username,
      pwd: password,
      roles: [{ role: 'readWrite', db: database }]
    });

    print('User created with username:', username);
    EOF
  load-data.js: |
    db = db.getSiblingDB('fiap');
    db.Users.insertMany([
      {
        "_id": "ad95fe76-122c-491a-ab92-9ba1682e0053",
        "name": "Joao Paulo",
        "email": "joao@fiap.com",
        "cpf": "90233730060",
        "phone": "1234567890",
        "createdAt": {
          "$date": "2023-07-08T18:54:41.080Z"
        },
        "updatedAt": {
          "$date": "2023-07-08T18:54:41.080Z"
        }
      }
    ]);
