apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-cm
data:
  init.js: |
    db = db.getSiblingDB('fiap');
    db.createUser({
      user: "application",
      pwd: "fiap123456",
      roles: [{ role: "readWrite", db: "fiap" }]
    });
  init-mongo.sh: |
    #!/bin/bash
    set -e

    mongo <<EOF
    var username = '$MONGO_INITDB_APP_USERNAME';
    var password = '$MONGO_INITDB_APP_PASSWORD';
    var database = '$MONGO_INITDB_APP_DATABASE';
    db = db.getSiblingDB(database);
    db.createUser({
      user: username,
      pwd: password,
      roles: [{ role: 'readWrite', db: database }]
    });

    print('User created with username:', username);
    EOF
