version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb-fiap"
    environment:
      - MONGO_INITDB_DATABASE=fiap
    ports:
      - 27017:27017
      - 27020:27020
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

  mongoimport:
    image: mongo:latest
    container_name: fiap-import
    volumes:
      - ./data-import/products.json:/data/products.json
    command: mongoimport --host mongodb:27017 --db fiap --collection Products --file ./data/products.json --jsonArray
    depends_on:
      - mongodb
    networks:
      - node-network

  app:
    build: ./fiap-application
    container_name: fiap-pedido
    ports:
      - 8080:8080
    environment:
        - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/fiap
    depends_on:
      - mongodb
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
