version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb-fiap"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
      - 27020:27020
    command: mongod

    networks:
      - fiap-network
  app:
    build: ./fiap-application
    container_name: fiap-pedido
    ports:
      - 8080:8080
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/fiap
    depends_on:
      - mongodb
    networks:
      - fiap-network
networks:
  fiap-network:
    driver: bridge
