export enum OrderStatus {
  RECEIVED = 'RECEIVED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
  IN_PREPARATION = 'IN_PREPARATION',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  FINISHED = 'FINISHED',
}
